### ISSUE TITLE
Doesn't work with ES6

### ISSUE THREAD

**Issue by seirdotexe** [hortopan/expressjs.routes.autoload#5]
As titled. Receiving the following error stack:

```
C:\Users\user\Documents\GitHub\express-example-server\node_modules\expressjs.routes.autoload\dist\index.js:37
                throw new Error("Error when loading route file: " + file + " [" + e.toString() + "]");
                      ^

Error: Error when loading route file: C:\Users\user\Documents\GitHub\express-example-server\lib\routes\login.js [Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\user\Documents\GitHub\express-example-server\lib\routes\login.js from C:\Users\user\Documents\GitHub\express-example-server\node_modules\expressjs.routes.autoload\dist\index.js not supported.
Instead change the require of login.js in C:\Users\user\Documents\GitHub\express-example-server\node_modules\expressjs.routes.autoload\dist\index.js to a dynamic import() which is available in all CommonJS modules.]
    at RoutesLoader (C:\Users\user\Documents\GitHub\express-example-server\node_modules\expressjs.routes.autoload\dist\index.js:37:23)
    at file:///C:/Users/user/Documents/GitHub/express-example-server/lib/server.js:27:9
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v18.2.0
```

**Comment by seirdotexe** [comment]
Update: I don't need this implementation anymore as I wrote it myself using async readdir.
